- name: Configure System
  hosts: localhost
  tasks:
    # Configure hostname.
    - name: Configure Hostname
      ansible.builtin.hostname:
        name: henrik-desktop
        use: systemd
      become: true

    # Mount disks.
    - name: Mount Data Disk
      ansible.posix.mount:
        src: LABEL=Data
        path: /mnt/Data
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: mounted
      become: true
    - name: Mount Backup Disk
      ansible.posix.mount:
        src: LABEL=Backup
        path: /mnt/Backup
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: mounted
      become: true

    # Configure GNOME (desktop environment).
    # Tell dconf to synchronize the binary database with a plain text keyfile in ~/.config/dconf/user.txt.
    # This allows us to backup and restore our GNOME settings using deja-dup.
    # Ref: https://wiki.gnome.org/Projects/dconf/SystemAdministrators
    - name: Configure GNOME User Profile
      ansible.builtin.copy:
        content: |
          service-db:keyfile/user
          user-db:user
          system-db:local
          system-db:site
          system-db:distro
        dest: /etc/dconf/profile/user
        mode: u=rw,g=r,o=r
      become: true

    # Configure Docker daemon to start at boot.
    - name: Configure Docker Daemon
      ansible.builtin.systemd_service:
        name: docker
        enabled: true
      become: true

    # Add user to Docker group.
    # This allows user to run Docker commands without sudo.
    - name: Add User to Docker Group
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        groups: docker
        append: true
      become: true
