- name: Configure System
  hosts: localhost
  become: true
  tasks:
    # Configure hostname:
    - name: Configure Hostname
      ansible.builtin.hostname:
        name: henrik-desktop
        use: systemd

    # Mount disks:
    - name: Mount Data Disk
      ansible.posix.mount:
        path: /mnt/Data
        src: LABEL=Data
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: present
    - name: Mount Backup Disk
      ansible.posix.mount:
        path: /mnt/Backup
        src: LABEL=Backup
        fstype: auto
        opts: nosuid,nodev,nofail,x-gvfs-show
        state: present

    # Configure GNOME (desktop environment).
    #
    # Tell dconf to synchronize the binary database with a plain text keyfile in
    # ~/.config/dconf/user.txt. This allows us to backup and restore our GNOME
    # settings using deja-dup.
    # Ref: https://wiki.gnome.org/Projects/dconf/SystemAdministrators
    - name: Configure GNOME to store user settings in home directory
      ansible.builtin.copy:
        content: |
          service-db:keyfile/user
          user-db:user
          system-db:local
          system-db:site
          system-db:distro
        dest: /etc/dconf/profile/user
